### ISSUE TITLE
Not resolved dependency

### ISSUE THREAD

**Issue by yakovenkoroman1993** [mvarnagiris/compose-navigation#1]
Added to your top level `build.gradle` :
`maven { url 'https://jitpack.io' }`
And added to app level `build.gradle` : 
`implementation 'com.github.mvarnagiris.compose-navigation:navigation:{latest_version}'`
Click Sync and see following error message:
**Failed to resolve: com.github.mvarnagiris.compose-navigation:navigation:{latest_version}**

**Comment by mvarnagiris** [comment]
You need to replace `{latest_version}` with `0.1.10`. So your dependency should look like
```
implementation 'com.github.mvarnagiris.compose-navigation:navigation:0.1.10'
```

**Comment by yakovenkoroman1993** [comment]
I would to like ask to reopen issue because this error occurs again

**Comment by yakovenkoroman1993** [comment]
![image](https://user-images.githubusercontent.com/13461433/81180939-e91cb480-8fd5-11ea-8667-42624342c696.png)

**Comment by mvarnagiris** [comment]
Can I see your top level `build.gradle`?

**Comment by yakovenkoroman1993** [comment]
> Can I see your top level `build.gradle`?

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.61'
    ext.compose_version = '0.1.0-dev03'
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0-alpha08'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
        flatDir {
            dirs 'libs'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by yakovenkoroman1993** [comment]
Well, sorry to waste your time then. I found my mistake - I put maven url to incorrect section ( `buildscript` instead of 'allProjects'). This issue should be closed. Thanks!

**Comment by mvarnagiris** [comment]
No worries :) I suspected that might be an issue that's why I asked to share this file. Glad you worked it out!
